# Terraform Variables
# Generated by setup wizard


# Cloudflare Configuration (configured via setup wizard)
# Note: CLOUDFLARE_API_TOKEN is in GitHub Secrets, not this file



# SSH access for your IP (configured via setup wizard)
# additional_ssh_ips = []  # Disabled in wizard
